local E, L, V, P, G, _ = unpack(ElvUI);
local AI = E:GetModule('AddonInstaller')

local ace3   = true               -- whether or not this database is a Ace3 profile
local name   = 'Skada'             -- the name of the addon
local dbname = 'SkadaDB'       -- name of the addon database

local function OnDemand(profile)  -- function that creates the "load on demand" database
	local database
	if profile == "Affinitii" then
		database = {
			["windows"] = {
				{
					["barheight"] = 17,
					["barslocked"] = true,
					["background"] = {
						["height"] = 133.6666717529297,
						["color"] = {
							["a"] = 0.2000000476837158,
							["b"] = 0,
						},
					},
					["hidden"] = true,
					["y"] = 39.89817468303028,
					["x"] = -7.334928625263729,
					["title"] = {
						["color"] = {
							["a"] = 1,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["font"] = "ElvUI Font",
						["fontsize"] = 15,
					},
					["point"] = "BOTTOMRIGHT",
					["barbgcolor"] = {
						["a"] = 1,
						["b"] = 0.3019607843137255,
						["g"] = 0.3019607843137255,
						["r"] = 0.3019607843137255,
					},
					["barcolor"] = {
						["g"] = 0.3019607843137255,
						["r"] = 0.3019607843137255,
					},
					["name"] = "HPS",
					["spark"] = false,
					["bartexture"] = "Polished Wood",
					["barwidth"] = 199.0832316080729,
					["barfontsize"] = 12,
					["mode"] = "Damage",
					["barfont"] = "ElvUI Font",
				}, -- [1]
				{
					["barheight"] = 17,
					["classicons"] = true,
					["barslocked"] = true,
					["clickthrough"] = false,
					["wipemode"] = "",
					["set"] = "current",
					["hidden"] = true,
					["y"] = 39.89824908834681,
					["barfont"] = "ElvUI Font",
					["name"] = "DPS",
					["display"] = "bar",
					["barfontflags"] = "",
					["classcolortext"] = false,
					["scale"] = 1,
					["reversegrowth"] = false,
					["barfontsize"] = 12,
					["barorientation"] = 1,
					["snapto"] = true,
					["point"] = "BOTTOMRIGHT",
					["x"] = -214.2783479639852,
					["spark"] = false,
					["bartexture"] = "Polished Wood",
					["barwidth"] = 199.0832316080729,
					["barspacing"] = 0,
					["barbgcolor"] = {
						["a"] = 1,
						["b"] = 0.3019607843137255,
						["g"] = 0.3019607843137255,
						["r"] = 0.3019607843137255,
					},
					["returnaftercombat"] = false,
					["barcolor"] = {
						["a"] = 1,
						["b"] = 0.8,
						["g"] = 0.3019607843137255,
						["r"] = 0.3019607843137255,
					},
					["mode"] = "Healing",
					["enabletitle"] = true,
					["classcolorbars"] = true,
					["modeincombat"] = "",
					["title"] = {
						["borderthickness"] = 2,
						["font"] = "ElvUI Font",
						["fontsize"] = 15,
						["fontflags"] = "",
						["color"] = {
							["a"] = 1,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["bordertexture"] = "None",
						["margin"] = 0,
						["texture"] = "Aluminium",
					},
					["buttons"] = {
						["segment"] = true,
						["menu"] = true,
						["mode"] = true,
						["report"] = true,
						["reset"] = true,
					},
					["background"] = {
						["borderthickness"] = 0,
						["height"] = 133.6666717529297,
						["color"] = {
							["a"] = 0.2000000476837158,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["bordertexture"] = "None",
						["margin"] = 0,
						["texture"] = "Solid",
					},
				}, -- [2]
			},
			["report"] = {
				["number"] = 12,
				["chantype"] = "whisper",
				["channel"] = "whisper",
				["target"] = "Affinitii",
				["mode"] = "Riggimon's Death",
			},
			["icon"] = {
				["minimapPos"] = 160.4361246854299,
				["hide"] = true,
			},
		}
	end

	if profile == "Repooc" then
		-- No Settings
	end

	if profile == "Darth" then
		database = {
			["spells"] = {
				["items"] = {
					["Самоцветы"] = {
						["Особые"] = false,
						["Синие"] = false,
						["Простые"] = false,
						["Оранжевые"] = false,
						["Желтые"] = false,
						["Зеленые"] = false,
						["Зубчатое колесо"] = false,
						["Радужные"] = false,
						["Красные"] = false,
						["Фиолетовые"] = false,
					},
					["Сумки"] = {
						["Сумка начертателя"] = false,
						["Сумка для продуктов"] = false,
						["Сумка инженера"] = false,
						["Сумка шахтера"] = false,
						["Сумка кожевника"] = false,
						["Сумка зачаровывателя"] = false,
						["Сумка ювелира"] = false,
						["Сумка"] = false,
						["Сумка травника"] = false,
						["Ящик для рыболовных снастей"] = false,
					},
					["Доспехи"] = {
						["Тканевые"] = false,
						["Разное"] = false,
						["Кожаные"] = false,
						["Щиты"] = false,
						["Кольчужные"] = false,
						["Визуальный эффект"] = false,
						["Латные"] = false,
					},
					["Задания"] = {
						["Задания"] = true,
					},
					["Оружие"] = {
						["Древковое"] = false,
						["Метательное"] = false,
						["Кистевое"] = false,
						["Одноручное дробящее"] = false,
						["Двуручные топоры"] = false,
						["Огнестрельное"] = false,
						["Двуручное дробящее"] = false,
						["Одноручные топоры"] = false,
						["Арбалеты"] = false,
						["Разное"] = false,
						["Луки"] = false,
						["Посохи"] = false,
						["Двуручные мечи"] = false,
						["Удочки"] = false,
						["Жезлы"] = false,
						["Одноручные мечи"] = false,
						["Кинжалы"] = false,
					},
					["Расходуемые"] = {
						["Зелья"] = true,
						["Еда и напитки"] = true,
						["Другое"] = false,
						["Эликсиры"] = true,
						["Настойки"] = true,
						["Улучшения"] = false,
						["Бинты"] = false,
						["Свитки"] = false,
					},
					["version"] = 1,
					["Боевые питомцы"] = {
						["Гуманоид"] = false,
						["Нежить"] = false,
						["Элементаль"] = false,
						["Животное"] = false,
						["Дракон"] = false,
						["Зверек"] = false,
						["Магический"] = false,
						["Механизм"] = false,
						["Летающий"] = false,
						["Водный"] = false,
					},
					["Разное"] = {
						["Питомцы"] = false,
						["Праздничные предметы"] = true,
						["Реагенты"] = false,
						["Другое"] = false,
						["Верховые животные"] = false,
						["Хлам"] = false,
					},
					["Символы"] = {
						["Паладин"] = false,
						["Шаман"] = false,
						["Друид"] = false,
						["Жрец"] = false,
						["Разбойник"] = false,
						["Монах"] = false,
						["Воин"] = false,
						["Чернокнижник"] = false,
						["Охотник"] = false,
						["Маг"] = false,
						["Рыцарь смерти"] = false,
					},
					["Хозяйственные товары"] = {
						["Наложение чар"] = true,
						["Трава"] = true,
						["Кожа"] = true,
						["Материалы"] = true,
						["Металл и камень"] = true,
						["Стихии"] = true,
						["Ткань"] = true,
						["Кулинария"] = true,
						["Чары для предметов"] = true,
						["Детали"] = true,
						["Ювелирное дело"] = true,
						["Другое"] = true,
						["Устройства"] = true,
						["Взрывчатка"] = true,
					},
					["Рецепты"] = {
						["Рыбная ловля"] = false,
						["Инженерное дело"] = false,
						["Кожевничество"] = false,
						["Первая помощь"] = false,
						["Начертание"] = false,
						["Ювелирное дело"] = false,
						["Книга"] = false,
						["Кузнечное дело"] = false,
						["Наложение чар"] = false,
						["Кулинария"] = false,
						["Алхимия"] = false,
						["Портняжное дело"] = false,
					},
				},
			},
			["frames"] = {
				["general"] = {
					["fontSize"] = 14,
					["showBuffs"] = false,
					["showPartyKills"] = false,
					["showDebuffs"] = false,
					["font"] = "ElvUI Font",
					["fontOutline"] = "2OUTLINE",
				},
				["power"] = {
					["fontSize"] = 16,
					["fontOutline"] = "2OUTLINE",
					["font"] = "ElvUI Font",
					["Width"] = 116,
					["Y"] = -92,
					["X"] = 364,
					["Height"] = 151,
					["enabledFrame"] = false,
				},
				["healing"] = {
					["fontSize"] = 16,
					["showFriendlyHealers"] = false,
					["fontOutline"] = "2OUTLINE",
					["insertText"] = "top",
					["Width"] = 171,
					["Y"] = -94,
					["X"] = 219,
					["Height"] = 158,
					["font"] = "ElvUI Font",
				},
				["outgoing"] = {
					["fontSize"] = 16,
					["Height"] = 242,
					["fontOutline"] = "2OUTLINE",
					["insertText"] = "top",
					["Width"] = 121,
					["Y"] = -207,
					["font"] = "ElvUI Font",
					["iconsSize"] = 10,
					["X"] = 898,
				},
				["critical"] = {
					["fontSize"] = 20,
					["iconsSize"] = 14,
					["fontOutline"] = "2OUTLINE",
					["insertText"] = "top",
					["Width"] = 171,
					["Y"] = -156,
					["X"] = 751,
					["Height"] = 138,
					["font"] = "ElvUI Font",
				},
				["procs"] = {
					["enabledFrame"] = false,
					["Width"] = 254,
					["Y"] = -63,
					["Height"] = 126,
				},
				["loot"] = {
					["fontSize"] = 12,
					["filterItemQuality"] = 2,
					["X"] = -1,
					["fontOutline"] = "2OUTLINE",
					["Y"] = -94,
					["font"] = "ElvUI Font",
					["Height"] = 155,
					["Width"] = 283,
				},
				["class"] = {
					["enabledFrame"] = false,
				},
				["damage"] = {
					["fontSize"] = 16,
					["X"] = -204,
					["Width"] = 161,
					["Y"] = -96,
					["font"] = "ElvUI Font",
					["Height"] = 156,
					["fontOutline"] = "2OUTLINE",
				},
			},
		}
	end
	
	return database
end

-- register the profile with the engine
AI:RegisterAddonProfile(name, ace3, dbname, OnDemand)