local E, L, V, P, G =  unpack(ElvUI); --Inport: Engine, Locales, ProfileDB, GlobalDB
local S = E:GetModule('Skins')

local function LoadSkin()
CharacterFrame:HookScript("OnShow", function( self ) PaperDollSidebarTabs:SetPoint("BOTTOMRIGHT", CharacterFrameInsetRight, "TOPRIGHT", -5, 0) end)
OutfitterFrame:HookScript("OnShow", function( self ) 
	self:StripTextures()
	self:SetTemplate("Transparent")
	OutfitterFrameTab1:Size(60,25)
	OutfitterFrameTab2:Size(60,25)
	OutfitterFrameTab3:Size(60,25)
	end)

OutfitterMainFrame:StripTextures()
OutfitterMainFrameScrollbarTrench:StripTextures()
OutfitterFrameTab1:StripTextures()
OutfitterFrameTab2:StripTextures()
OutfitterFrameTab3:StripTextures()
OutfitterFrameTab1:ClearAllPoints()
OutfitterFrameTab2:ClearAllPoints()
OutfitterFrameTab3:ClearAllPoints()
OutfitterFrameTab1:Point("TOPLEFT", OutfitterFrame, "BOTTOMRIGHT", -65, -2)
OutfitterFrameTab2:Point("LEFT", OutfitterFrameTab1, "LEFT", -65, 0)
OutfitterFrameTab3:Point("LEFT", OutfitterFrameTab2, "LEFT", -65, 0)
S:HandleButton(OutfitterFrameTab1, true)
OutfitterFrameTab1:Size(60,25)
S:HandleButton(OutfitterFrameTab2, true)
OutfitterFrameTab2:Size(60,25)
S:HandleButton(OutfitterFrameTab3, true)
S:HandleButton(OutfitterButton, true)
OutfitterButton:ClearAllPoints()
OutfitterButton:SetPoint("TOPRIGHT", CharacterFrame, "TOPRIGHT", -8, -30)
PaperDollSidebarTab3:ClearAllPoints()
PaperDollSidebarTab3:Point("RIGHT", OutfitterButton, "LEFT", -6, 0)

S:HandleScrollBar(OutfitterMainFrameScrollFrameScrollBar)
S:HandleButton(OutfitterNewButton, true)
S:HandleButton(OutfitterEnableNone, true)
S:HandleButton(OutfitterEnableAll, true)
S:HandleCloseButton(OutfitterCloseButton)

OutfitterButton:StripTextures()
OutfitterButton:Size(32, 20)
OutfitterButton.tex = OutfitterButton:CreateTexture(nil, 'OVERLAY')
OutfitterButton.tex:Point('TOPLEFT', OutfitterButton, 'TOPLEFT', 1, -1)
OutfitterButton.tex:Point('BOTTOMRIGHT', OutfitterButton, 'BOTTOMRIGHT', -1, 1)
OutfitterButton.tex:SetTexture("Interface\\AddOns\\ElvUI_SLE\\textures\\outfitter")
OutfitterSlotEnables:SetFrameStrata("HIGH")
end

S:RegisterSkin('Outfitter', LoadSkin)